# -*- coding: utf-8 -*-
"""kpi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QuUVX4HrTQ5j8dJ5_mFLqpn0C6zq4d7i
"""

# ==========================================
# Load Libraries
# ==========================================
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



st.set_page_config(page_title="Sales Dashboard", layout="wide")

st.title("📊 Sales Dashboard")
st.write("Sample Superstore Dashboard")


# ==========================================
# Load Dataset
# ==========================================

# Put "Sample_ Superstore.csv"
# in the same folder as KPI.py

df = pd.read_csv("Sample_ Superstore.csv")

st.success("Dataset Loaded Successfully!")

st.subheader("Dataset Preview")

st.dataframe(df.head())

# ==========================================
# Dataset Preview
# ==========================================

print(df.head())

print("\nDataset Information:\n")
print(df.info())

print("\nMissing Values:\n")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

# ==========================================
# Data Cleaning
# ==========================================

df.drop_duplicates(inplace=True)

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="mixed"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="mixed"
)

df["Shipping Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

print("\nCleaning Completed Successfully!")

print(df.head())


# ========== Filters ==========

st.sidebar.header("Filters")

# Region Filter
selected_region = st.sidebar.selectbox(
    "Select Region",
    ["All"] + list(df["Region"].unique())
)

if selected_region == "All":
    filtered_df = df.copy()
else:
    filtered_df = df[df["Region"] == selected_region]


# Category Filter
selected_category = st.sidebar.selectbox(
    "Select Category",
    ["All"] + list(filtered_df["Category"].unique())
)

if selected_category != "All":
    filtered_df = filtered_df[
        filtered_df["Category"] == selected_category
    ]
# ==========================================
# KPI Monitoring
# ==========================================

# Total Sales
total_sales = filtered_df["Sales"].sum()

# Total Profit
total_profit = filtered_df["Profit"].sum()

# Total Orders
total_orders = filtered_df["Order ID"].nunique()

# Average Sales
average_sales = filtered_df["Sales"].mean()

# Average Discount
average_discount = filtered_df["Discount"].mean()

# Average Shipping Days
average_shipping = filtered_df["Shipping Days"].mean()

# Profit Margin
profit_margin = (total_profit / total_sales) * 100

print("========== KPI Monitoring ==========\n")

# print(f"Total Sales: ${total_sales:,.2f}")
# print(f"Total Profit: ${total_profit:,.2f}")
# print(f"Total Orders: {total_orders}")
# print(f"Average Sales: ${average_sales:.2f}")
# print(f"Average Discount: {average_discount:.2%}")
# print(f"Average Shipping Days: {average_shipping:.2f}")
# print(f"Profit Margin: {profit_margin:.2f}%")



st.header("📈 KPI Dashboard")

col1, col2, col3 = st.columns(3)

with col1:
    st.metric("💰 Total Sales", f"${total_sales:,.2f}")

with col2:
    st.metric("💵 Total Profit", f"${total_profit:,.2f}")

with col3:
    st.metric("📦 Total Orders", total_orders)

col4, col5, col6 = st.columns(3)

with col4:
    st.metric("📊 Avg Sales", f"${average_sales:.2f}")

with col5:
    st.metric("🏷 Avg Discount", f"{average_discount:.2%}")

with col6:
    st.metric("🚚 Avg Shipping", f"{average_shipping:.2f} Days")

st.metric("📈 Profit Margin", f"{profit_margin:.2f}%")

# ==========================================
# Sales by Category
# ==========================================

sales_by_category = filtered_df.groupby("Category")["Sales"].sum().sort_values(ascending=False)

# plt.figure(figsize=(8,5))

# plt.bar(
#     sales_by_category.index,
#     sales_by_category.values
# )

# plt.title("Sales by Category")
# plt.xlabel("Category")
# plt.ylabel("Sales")

# plt.show()


fig, ax = plt.subplots(figsize=(8,5))

ax.bar(
    sales_by_category.index,
    sales_by_category.values
)

ax.set_title("Sales by Category")

st.pyplot(fig)

# ==========================================
# Profit by Region
# ==========================================

profit_by_region = filtered_df.groupby("Region")["Profit"].sum()

# plt.figure(figsize=(8,5))

# plt.bar(
#     profit_by_region.index,
#     profit_by_region.values
# )

# plt.title("Profit by Region")
# plt.xlabel("Region")
# plt.ylabel("Profit")

# plt.show()



fig, ax = plt.subplots(figsize=(8,5))

ax.bar(
     profit_by_region.index,
     profit_by_region.values
 )

ax.set_title("profit by Category")

st.pyplot(fig)


# ==========================================
# Monthly Sales Trend
# ==========================================

monthly_sales = filtered_df.groupby(
    filtered_df["Order Date"].dt.to_period("M")
)["Sales"].sum()

monthly_sales.index = monthly_sales.index.astype(str)

# plt.figure(figsize=(12,5))

# plt.plot(
#     monthly_sales.index,
#     monthly_sales.values,
#     marker="o"
# )

# plt.xticks(rotation=45)

# plt.title("Monthly Sales Trend")
# plt.xlabel("Month")
# plt.ylabel("Sales")

# plt.show()


fig, ax = plt.subplots(figsize=(8,5))

ax.plot(
     monthly_sales.index,
      monthly_sales.values,
      marker="o", 
      

 )

ax.set_title("Monthly Sales Trend")
ax.set_xlabel("Month")
ax.set_ylabel("Sales")

st.pyplot(fig)





# ==========================================
# Top 10 Products
# ==========================================

top_products = filtered_df.groupby(
    "Product Name"
)["Sales"].sum().sort_values(
    ascending=False
).head(10)

# plt.figure(figsize=(10,6))

# plt.barh(
#     top_products.index,
#     top_products.values
# )

# plt.title("Top 10 Products")

# plt.xlabel("Sales")

# plt.gca().invert_yaxis()

# plt.show()

fig, ax = plt.subplots(figsize=(8,5))

ax.barh(
    top_products.index,
     top_products.values

 )

ax.set_title("Top 10 Products")
ax.set_xlabel("Sales")
ax.invert_yaxis()

st.pyplot(fig)



# ==========================================
# Recommendation Logic
# ==========================================

# print("\n========== Recommendations ==========\n")

# recommendations = []

# # Profit Margin
# if profit_margin < 10:
#     recommendations.append(
#         "Review pricing strategy to improve profit margin."
#     )

# # Shipping
# if average_shipping > 4:
#     recommendations.append(
#         "Reduce shipping time to improve customer satisfaction."
#     )

# # Discount
# if average_discount > 0.20:
#     recommendations.append(
#         "High discounts detected. Consider reducing discounts."
#     )

# # Top Category
# top_category = df.groupby("Category")["Sales"].sum().idxmax()

# recommendations.append(
#     f"Increase inventory for {top_category} products."
# )

# # Top Region
# top_region = df.groupby("Region")["Sales"].sum().idxmax()

# recommendations.append(
#     f"Increase marketing campaigns in {top_region} region."
# )

# # Print Recommendations

# for i, rec in enumerate(recommendations, start=1):
#     print(f"{i}. {rec}")


# ==========================================
# Recommendation Logic
# ==========================================

st.header("💡 Business Recommendations")

recommendations = []

if profit_margin < 10:
    recommendations.append(
        "Review pricing strategy to improve profit margin."
    )

if average_shipping > 4:
    recommendations.append(
        "Reduce shipping time to improve customer satisfaction."
    )

if average_discount > 0.20:
    recommendations.append(
        "High discounts detected. Consider reducing discounts."
    )

top_category = filtered_df.groupby("Category")["Sales"].sum().idxmax()

recommendations.append(
    f"Increase inventory for {top_category} products."
)

top_region = filtered_df.groupby("Region")["Sales"].sum().idxmax()

recommendations.append(
    f"Increase marketing campaigns in {top_region} region."
)

# Display Recommendations
for rec in recommendations:
    st.success(rec)

# ==========================================
# Automated Insights
# ==========================================

# print("\n========== Automated Insights ==========\n")

# # Top Selling Category
# top_category = df.groupby("Category")["Sales"].sum().idxmax()
# top_category_sales = df.groupby("Category")["Sales"].sum().max()

# print(f"Top Selling Category : {top_category}")
# print(f"Category Sales       : ${top_category_sales:,.2f}\n")

# # Top Region
# top_region = df.groupby("Region")["Sales"].sum().idxmax()
# top_region_sales = df.groupby("Region")["Sales"].sum().max()

# print(f"Top Sales Region     : {top_region}")
# print(f"Region Sales         : ${top_region_sales:,.2f}\n")

# # Top Product
# top_product = df.groupby("Product Name")["Sales"].sum().idxmax()
# top_product_sales = df.groupby("Product Name")["Sales"].sum().max()

# print(f"Best Selling Product : {top_product}")
# print(f"Product Sales        : ${top_product_sales:,.2f}\n")

# # Most Profitable Category
# profit_category = df.groupby("Category")["Profit"].sum().idxmax()
# profit_value = df.groupby("Category")["Profit"].sum().max()

# print(f"Most Profitable Category : {profit_category}")
# print(f"Profit                  : ${profit_value:,.2f}\n")

# ==========================================
# Automated Insights
# ==========================================

st.header("📊 Automated Insights")

# Top Selling Category
top_category = filtered_df.groupby("Category")["Sales"].sum().idxmax()
top_category_sales = filtered_df.groupby("Category")["Sales"].sum().max()

st.write(f"🏆 **Top Selling Category:** {top_category}")
st.write(f"💰 **Category Sales:** ${top_category_sales:,.2f}")

# Top Region
top_region = filtered_df.groupby("Region")["Sales"].sum().idxmax()
top_region_sales = filtered_df.groupby("Region")["Sales"].sum().max()

st.write(f"🌍 **Top Sales Region:** {top_region}")
st.write(f"💵 **Region Sales:** ${top_region_sales:,.2f}")

# Top Product
top_product = filtered_df.groupby("Product Name")["Sales"].sum().idxmax()
top_product_sales = filtered_df.groupby("Product Name")["Sales"].sum().max()

st.write(f"📦 **Best Selling Product:** {top_product}")
st.write(f"💲 **Product Sales:** ${top_product_sales:,.2f}")

# Most Profitable Category
profit_category = filtered_df.groupby("Category")["Profit"].sum().idxmax()
profit_value = filtered_df.groupby("Category")["Profit"].sum().max()

st.write(f"📈 **Most Profitable Category:** {profit_category}")
st.write(f"💸 **Profit:** ${profit_value:,.2f}")

# Business Status
# print("========== Business Status ==========\n")

# if total_profit > 0:
#     print("Business is profitable.")
# else:
#     print("Business is operating at a loss.")

# if average_discount > 0.20:
#     print("High discounts may reduce profitability.")

# if average_shipping > 4:
#     print("Shipping time is high.")

# print("\n========== End of Report ==========")

st.header("📌 Business Status")

if total_profit > 0:
    st.success("Business is profitable.")
else:
    st.error("Business is operating at a loss.")

if average_discount > 0.20:
    st.warning("High discounts may reduce profitability.")

if average_shipping > 4:
    st.warning("Shipping time is high.")






with st.expander("📄 View Dataset"):
    st.dataframe(filtered_df)




from joblib import load
model = load("model.pkl")




page = st.sidebar.selectbox(
    "Select Page",
    [
        "Dashboard",
        "ML Prediction"
    ]
)


if page == "ML Prediction":

    st.header("ML Prediction")

    sales_input = st.number_input("Sales")
    discount_input = st.number_input("Discount")
    quantity_input = st.number_input("Quantity")

    category_input = st.selectbox(
        "Category",
        df["Category"].unique()
    )

    subcategory_input = st.selectbox(
        "Sub-Category",
        df["Category"].unique()
    )

    region_input = st.selectbox(
        "Region",
        df["Region"].unique()
    )

    segment_input = st.selectbox(
        "Segment",
        df["Segment"].unique()
    )

    shipmode_input = st.selectbox(
        "Ship Mode",
        df["Ship Mode"].unique()
    )


    if st.button("predict"):

        input_data = pd.DataFrame({

            "Sales":[sales_input],
            "Discount":[discount_input],
            "Quantity":[quantity_input],
            "Category":[category_input],
            "Sub-Category":[subcategory_input],
            "Region":[region_input],
            "Segment":[segment_input],
            "Ship Mode":[shipmode_input]
        })



        prediction = model.predict(input_data)

        probability = model.predict(input_data)


        if prediction[0] == 1:
            st.success(
                f"Profitable Order     Probability: {probability[0][1]:.2%}"
            )

        else:
            st.error(
                f"Not Profitable Order    Probability: {probability[0],[0]:.2%}"
            )









 