# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bmTSsz2ldC1qAvFdWS86hKygXQ56k5pC
"""

# ==========================================
# Smart Retail Analytics
# Classification Model
# Predict Profitable Order
# ==========================================

# ==========================================
# Import Libraries
# ==========================================

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

from joblib import dump


# ==========================================
# Load Dataset
# ==========================================

df = pd.read_csv("Sample_ Superstore.csv")

print("Dataset Loaded Successfully!")


# ==========================================
# Data Cleaning
# ==========================================

df.drop_duplicates(inplace=True)

df["Order Date"] = pd.to_datetime(df["Order Date"], format="mixed")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="mixed")

df["Shipping Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

print("Cleaning Completed Successfully!")


# ==========================================
# Create Target Column
# ==========================================

df["Profitable"] = (df["Profit"] > 0).astype(int)

print("\nTarget Distribution\n")

print(df["Profitable"].value_counts())


# ==========================================
# Feature Selection
# ==========================================

X = df[
    [
        "Sales",
        "Discount",
        "Quantity",
        "Category",
        "Sub-Category",
        "Region",
        "Segment",
        "Ship Mode"
    ]
]

y = df["Profitable"]


# ==========================================
# Categorical Features
# ==========================================

categorical_features = [

    "Category",

    "Sub-Category",

    "Region",

    "Segment",

    "Ship Mode"

]

preprocessor = ColumnTransformer(

    transformers=[

        (

            "cat",

            OneHotEncoder(handle_unknown="ignore"),

            categorical_features

        )

    ],

    remainder="passthrough"

)


# ==========================================
# Train Test Split
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.20,

    random_state=42,

    stratify=y

)


# ==========================================
# Build Pipeline
# ==========================================

model = Pipeline(

    steps=[

        ("preprocessor", preprocessor),

        (

            "classifier",

            RandomForestClassifier(

                n_estimators=200,

                random_state=42

            )

        )

    ]

)


# ==========================================
# Train Model
# ==========================================

model.fit(X_train, y_train)

print("\nModel Trained Successfully!")


# ==========================================
# Prediction
# ==========================================

y_pred = model.predict(X_test)


# ==========================================
# Evaluation
# ==========================================

accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(y_test, y_pred)

recall = recall_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred)

cm = confusion_matrix(y_test, y_pred)

print("\n========== MODEL EVALUATION ==========\n")

print(f"Accuracy  : {accuracy:.4f}")

print(f"Precision : {precision:.4f}")

print(f"Recall    : {recall:.4f}")

print(f"F1 Score  : {f1:.4f}")

print("\nConfusion Matrix\n")

print(cm)

print("\nClassification Report\n")

print(classification_report(y_test, y_pred))


# ==========================================
# Save Model
# ==========================================

dump(model, "model.pkl")

print("\nModel Saved Successfully!")

print("File Name : model.pkl")

from sklearn.metrics import roc_auc_score

y_prob = model.predict_proba(X_test)[:, 1]

auc = roc_auc_score(y_test, y_prob)

print(f"\nROC AUC Score : {auc:.4f}")

